# Generated by Django 3.2.8 on 2021-10-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
