# Generated by Django 3.2.8 on 2021-12-03 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extensions.upload_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Do not fill in here', unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='Image')),
                ('summary', models.TextField(max_length=400, verbose_name='Summary')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish time')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('special', models.BooleanField(default=False, verbose_name='Is special Blog ?')),
                ('status', models.CharField(choices=[('p', 'publish'), ('d', 'draft')], max_length=1, verbose_name='Status')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ManyToManyField(blank=True, default=None, related_name='blogs', to='blog_category.Category', verbose_name='Categories')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='blogs_dislike', to=settings.AUTH_USER_MODEL, verbose_name='Dislikes')),
                ('likes', models.ManyToManyField(blank=True, related_name='blogs_like', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-publish', '-updated'],
            },
        ),
    ]
